image: python:3.8
stages:
  - test

lint:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -U mypy
    - mypy --config-file pyproject.toml .
  allow_failure: true

dvc:
  stage: test
  script:
    - pip install dvc==3.42.0  dvc-s3==3.0.1
    - dvc remote add origin $MINIO_URL
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - dvc pull
  allow_failure: false
  needs: ["lint"]

test_unit:
  stage: test
  script:
    - pip install -r requirements.txt
    - dvc remote add origin $MINIO_URL
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - export PYTHONPATH=./app:$PYTHONPATH
    - dvc pull
    - pytest ./test/test_healthcheck.py
    - pytest ./test/test_predict.py
  allow_failure: false
  needs: ["dvc"]


