image: python:3.8
stages:
  - test

lint:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -U mypy
    - mypy --config-file pyproject.toml .
  allow_failure: true

dvc:
  stage: test
  script:
    - pip install -r requirements.txt
    - dvc remote add origin $MINIO_URL
    - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
    - dvc pull
    - if [ $? -eq 0 ]; then
      echo "DVC pull successful"
      else
      echo "DVC pull failed"
      exit 1
      fi
  allow_failure: false

test_unit:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest ./test/test_predict.py
    - pytest ./test/test_healthcheck.py
  allow_failure: false
  needs: ["dvc"]


